#!/usr/bin/env ruby

require 'bio'

dna_string = 'ATATGCTCCACTACCGAGGTCCGGTGATTCTTTGATTTCTTTTCTATATAAAAGATACTC
TGACGACACGTCTTGCCAGTGGTGCGTAAACGTAGACTGTCTCATGCCGCTTTTTAGTAA
GATCGCATATGTGATTGTCACACGTCGACAACCCTGTCAAGAGTGCTGAAAGGGACGCCA
TACGAGGGTAGCAGTCCTGTCACTAGCGTTAGTCCTCTGTAAGGGAAGCTTTTACAGGCA
GCAAGCGGCTCTCTGTTCGTTGTGTAGGACTGTCTGTTAAACCTTGTAAACGATGTGAGA
ACTGAGTCGTCCCCGCCGAACCCTCGAGCGAGATGTCGTTGTTGTCTATCAGTCCCGGGA
GGACGGACTCGTTCCCTGTCGCTGGCACGAATGACCTCTATCGAAGGCTTACCGGCTGAT
TCCAGCGTCACGAGTTATTTGGAACATAGGTGGGCGCCTCAAGTATCAGCAGCACCGGTG
CTTAACCTCCCGCAGTCGAATTGAGTACTGTCCTAGGTTAGACGAGGGGGGTCGAAGTTA
TCAGACATGCATGGTTGGCCGCTTAACTTACCCAAACTCGCATCGTCCTATCTTCCATCC
GCCCTGTAGAGGTATAATGGCGGCTCAAGGAACAGAATTCACAGCAAGCTGGTACGCTTT
AATACCACCCTTGCATACCGGCTTGTTCAGGCCACTGACACATCCAGGGAGCATAGGCTA
TAGACTCTAAAGACTCATGCCTAGTATTCCTGGACCTCAAGTTACGTGCGGCGCACAGAA
ACCTGGCTCGTCCTTTATACCGTTCATTGGTCATTCTCGACACGTCAACTATTCTAAATC
GATTTCGGCACCTTTCCCAGGCGTTAAATGAACGTCCACTTCAGTCCCTGGAAAGTCCTC
ACCCACGTCGCCCGTGACCCTCGATGTACCACTCTGCATATTCGTTCGATAT'

dnaseq=Bio::Sequence.auto(dna_string)

seq = dnaseq.seq
rc_seq = dnaseq.reverse_complement.reverse

n = seq.length

(0..n-1).each do |start_i|
  ml = [n-start_i,12].min
  lengths = (4..ml)
  lengths.each do |j|
    s = start_i
    sseq = seq[start_i,j]
    rcseq = rc_seq[start_i,j].reverse
    if ( sseq == rcseq)
      puts "#{start_i+1} #{j}"
    end
  end
end
